name: Trigger E2E tests

on:
  push:
    branches:
      - main

jobs:
  trigger-e2e-tests:
    name: Trigger E2E tests for ${{ matrix.stage }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        stage: [dev, preprod, prod]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.stage }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: ${{matrix.node-version}}

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ secrets.TELLIHEATH_READINGS_E2E_APP_ID }}
          private-key: ${{ secrets.TELLIEALTH_READINGS_E2E_APP_PRIVATE_KEY }}
          repositories: |
            tellihealth-api-e2e

      - name: Trigger E2E API tests workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/tellihealth/tellihealth-api-e2e/dispatches \
            -d '{"event_type": "tellihealth-rpm-api-spec", "client_payload": {"stage": "${{ matrix.stage }}"}}'
